heat_template_version: 2015-04-30

description: >
  Definition of a TinyCore OS image
resources:
  image:
    type: OS::Glance::Image
    properties:
      name: CORE
      is_public: True
      container_format: bare  
      disk_format: iso
      location: http://artifact_server/image/current-core

outputs:
  OS::stack_id:
    value: {get_resource: image}  
